I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tl/english/script.rpy", line 1369, in script
    old "No"
  File "game/tl/english/script.rpy", line 1369, in script
    old "No"
Exception: A translation for "No" already exists at game/tl/english/script.rpy:1356.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/tl/english/script.rpy", line 1369, in script
    old "No"
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/tl/english/script.rpy", line 1369, in script
    old "No"
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 2751, in execute
    renpy.translation.add_string_translation(self.language, self.old, self.new, newloc)
  File "D:\renpy-8.0.3-sdk\renpy\translation\__init__.py", line 475, in add_string_translation
    stl.add(old, new, newloc)
  File "D:\renpy-8.0.3-sdk\renpy\translation\__init__.py", line 415, in add
    raise Exception("A translation for \"{}\" already exists at {}:{}.".format(
Exception: A translation for "No" already exists at game/tl/english/script.rpy:1356.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Sequences 1.0
Wed May 31 02:47:51 2023
